// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Greeting$Whatever = require("./Greeting.bs.js");

console.log("Hello World");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Greeting$Whatever.make("Parcel", /* array */[])), "app");

/*  Not a pure module */
